### ISSUE TITLE
Не зарегестрирован магазин по координатам -271 137.

### ISSUE THREAD

**Issue by HotRikardo228** [mcrpg/work#10]
Не зарегестрирован магазин по координатам -271 137. 
![Screenshot_20200102-122609_Minecraft](https://user-images.githubusercontent.com/59420530/71660523-5e445880-2d5c-11ea-878e-a411f442485d.jpg)

**Comment by HotRikardo228** [comment]
log 30m - зарегестрировал часть магазина.
![Screenshot_20200102-135203_Minecraft](https://user-images.githubusercontent.com/59420530/71663725-59d16d00-2d67-11ea-9874-5d9f029935ae.jpg)

**Comment by FirzMob** [comment]
Таблички расставлены в неправильном порядке.
![image](https://user-images.githubusercontent.com/57770811/71724155-ab9df400-2e48-11ea-92f2-599d81c4d611.png)
![image](https://user-images.githubusercontent.com/57770811/71724166-b8bae300-2e48-11ea-965e-8400209ffac9.png)

**Comment by ProCompTEAM** [comment]
Таск закрыт в виду отсутствия необходимости его реализации и ресурсозатратности. Если это будет необходимо, он может быть открыт снова.

**Comment by ProCompTEAM** [comment]
Все обновления по таску в #26
