### ISSUE TITLE
Записать видеоролик об использовании GITHUB на проекте

### ISSUE THREAD

**Issue by mcrpg** [mcrpg/work#12]
Необходимо записать видео ролик, в котором будет подробно объяснено для чего нужна подобная система на проекте, а так же как правильно создавать issue, для чего нужны лэйблы(теги), редактирование контента и использование вики.

Затем его необходимо **персонально** распространить среди всего состава администрации. #4

**Comment by FirzMob** [comment]
Начинаю записывать!

**Comment by mcrpg** [comment]
> 
> 
> Скачивание программу по записи видео. Начинаю записывать!

статус тогда проставляй: В РАБОТЕ

**Comment by FirzMob** [comment]
Ролик в обработке.

**Comment by FirzMob** [comment]
![Lesson on GitHub](https://vk.com/im?sel=c119&z=video201066003_456239114%2F26cbea0e71f26d8fd9)
Задание выполнено! Видеоролик опубликован администрации.

**Comment by mcrpg** [comment]
Новые задания:
- распространить среди администрации
- провести экзамен на 5 вопросов после видео

**Comment by FirzMob** [comment]
Находится на рассмотрении.

**Comment by FirzMob** [comment]
Экзамен был проведён. 
Список не сдавших:
[Майкл Святковский](https://vk.com/5foxpe)
[Максим Веремейчик](https://vk.com/id554251679)
[Дима Чернышев](https://vk.com/id310728553)
