### ISSUE TITLE
Нереалистичный поворот проводов:  добавить столб ЛЭП

### ISSUE THREAD

**Issue by mcrpg** [mcrpg/work#15]
Нереалистичный поворот проводов:  добавить столб ЛЭП в районе 363 183
![изображение](https://user-images.githubusercontent.com/59419128/71672697-cc524500-2d87-11ea-9d00-c0a32ab94afc.png)
![изображение](https://user-images.githubusercontent.com/59419128/71672706-d3795300-2d87-11ea-885b-d43e35be5e5c.png)

**Comment by Makcim212** [comment]
Log 30m - Исправил нереалистичный поворот проводов. 
![Screenshot_20200104_134447_com mojang minecraftpe](https://user-images.githubusercontent.com/59478711/71764479-6f769c00-2ef9-11ea-98c7-f30ca059b393.jpg) 
![Screenshot_20200104_134459_com mojang minecraftpe](https://user-images.githubusercontent.com/59478711/71764486-77364080-2ef9-11ea-9ce2-dff07771b8bd.jpg)
