### ISSUE TITLE
Не зарегестрирован дом по координатам 759 67

### ISSUE THREAD

**Issue by HotRikardo228** [mcrpg/work#19]
Не зарегестрирован дом по координатам 759 67
Дом находится на ул. Административная (/gps Административная). Подъезд D-2
![Screenshot_20200102-223102_Minecraft](https://user-images.githubusercontent.com/59420530/71688825-b22d5c80-2db1-11ea-9dab-ba513a6f3a7e.jpg)

**Comment by HotRikardo228** [comment]
Найдена ошибка. Не могу зарегестрировать квартиру. 
![Screenshot_20200102-233125_Minecraft](https://user-images.githubusercontent.com/59420530/71691504-a2fddd00-2db8-11ea-98fc-28653c143b17.jpg)

**Comment by mcrpg** [comment]
пока отложим. позже разберемся в чем там проблема

**Comment by mcrpg** [comment]
необходимо разобраться по тех. части проблемы

**Comment by ProCompTEAM** [comment]
Таск закрыт в виду отсутствия необходимости его реализации и ресурсозатратности. Если это будет необходимо, он может быть открыт снова.
