### ISSUE TITLE
Достроить стену загона

### ISSUE THREAD

**Issue by Aptemius2** [mcrpg/work#22]
Достроить стену загона в лучшем качестве
![Снимок экрана (225)](https://user-images.githubusercontent.com/59419304/71723644-768ca400-2e3e-11ea-9f6f-271c66e408e2.png)

**Comment by ProCompTEAM** [comment]
Тег дизайна прикрепляется только для тасков, связанных с дизайном графическим. Достаточно лишь прикрепить метку о том, что таск для строителей.

**Comment by ProCompTEAM** [comment]
И разве, кстати, там не все правильно? По моему так и задумывалось, или нет?

**Comment by Aptemius2** [comment]
а, точно. Это же колизей
