### ISSUE TITLE
Оживить участок возле озера -332 178

### ISSUE THREAD

**Issue by FirzMob** [mcrpg/work#25]
Оживить участок возле озера -332 178 
![image](https://user-images.githubusercontent.com/57770811/71724608-4a772000-2e4a-11ea-823a-67f2f4929513.png)
![image](https://user-images.githubusercontent.com/57770811/71724620-54991e80-2e4a-11ea-9a28-6f2328b9e9e9.png)

**Comment by Makcim212** [comment]
30m  Отсроил участок деревьями 
![Screenshot_20200103_185926_com mojang minecraftpe](https://user-images.githubusercontent.com/59478711/71734351-d09c6200-2e5c-11ea-8a0a-bd3c936d4c97.jpg)
