### ISSUE TITLE
Какие-то непонятки с домом в центре города

### ISSUE THREAD

**Issue by mcrpg** [mcrpg/work#30]
В центре города нарушена постройка. Привести в приемлемый вид, разработав с руководителем план по улучшению строения. 
![изображение](https://user-images.githubusercontent.com/59419128/71762882-6d571200-2ee6-11ea-8ae9-29a700b9f3b1.png)
![изображение](https://user-images.githubusercontent.com/59419128/71762884-747e2000-2ee6-11ea-96f6-7f39c6fe6d66.png)
![изображение](https://user-images.githubusercontent.com/59419128/71762886-7c3dc480-2ee6-11ea-8acd-83032789a4d3.png)
![изображение](https://user-images.githubusercontent.com/59419128/71762890-8bbd0d80-2ee6-11ea-94c2-ba343f1e4cb7.png)

**Comment by Makcim212** [comment]
Log 30m - Исправил дом   ##
![Screenshot_20200104_123859_com mojang minecraftpe](https://user-images.githubusercontent.com/59478711/71763742-6f25d300-2ef0-11ea-905b-80e1c07a17b8.jpg) 
![Screenshot_20200104_123556_com mojang minecraftpe](https://user-images.githubusercontent.com/59478711/71763744-764ce100-2ef0-11ea-8cf7-da51f5d8a460.jpg) 
![Screenshot_20200104_123645_com mojang minecraftpe](https://user-images.githubusercontent.com/59478711/71763746-7cdb5880-2ef0-11ea-8c9f-2e40d591d2ce.jpg)

**Comment by Makcim212** [comment]
Log 30m - Исправил дом 
![Screenshot_20200104_123859_com mojang minecraftpe](https://user-images.githubusercontent.com/59478711/71763757-9e3c4480-2ef0-11ea-8bde-928ae8f8def0.jpg) 
![Screenshot_20200104_123645_com mojang minecraftpe](https://user-images.githubusercontent.com/59478711/71763759-a1cfcb80-2ef0-11ea-817d-7fa145e7dc66.jpg). 
![Screenshot_20200104_123533_com mojang minecraftpe](https://user-images.githubusercontent.com/59478711/71763761-a8f6d980-2ef0-11ea-9c48-70662a14b206.jpg)

**Comment by Makcim212** [comment]
Iog 30m - Исправил дом 
![Screenshot_20200104_123859_com mojang minecraftpe](https://user-images.githubusercontent.com/59478711/71763784-fc692780-2ef0-11ea-8c65-661e277ed967.jpg) 
![Screenshot_20200104_123645_com mojang minecraftpe](https://user-images.githubusercontent.com/59478711/71763785-fffcae80-2ef0-11ea-8692-715235e62004.jpg)
![Screenshot_20200104_123556_com mojang minecraftpe](https://user-images.githubusercontent.com/59478711/71763786-03903580-2ef1-11ea-87e1-a1076da67505.jpg)
