### ISSUE TITLE
Адаптация состава

### ISSUE THREAD

**Issue by mcrpg** [mcrpg/work#4]
Произвести адаптацию состава к данному ресурсу до **03.01.2020**

**Comment by FirzMob** [comment]
Я ознакомлен и в скором времени готов начать выполнять задачу.

**Comment by Aptemius2** [comment]
готов готовить работу

**Comment by mcrpg** [comment]
#time 3h 30m - адаптация высшего состава

**Comment by StormLVV** [comment]
Администратор состава А-4 к дальнейшим указаниям готов!
