### ISSUE TITLE
Сбор сведений о невозможности зайти на сервер (всем)

### ISSUE THREAD

**Issue by mcrpg** [mcrpg/work#6]
Пожалуйста, ниже в комментариях напишите можете ли вы зайти на сервер по состоянию на 01.01.2020. 

Если вы можете зайти, напишите: "**Я могу зайти**"
Если же нет, то: "**Не могу зайти: <ваша версия игры>, <страна>, <ваш интернет>**"

**IP** и порт узнавайте **у своего** руководителя.
#
(Tech) Ссылается на https://github.com/pmmp/PocketMine-MP/issues/3127

**Comment by mcrpg** [comment]
Желательно прикрепить скриншот*

**Comment by StormLVV** [comment]
Основные варианты развития событий:
1) Успешный вход на сервер и кик через 10 секунд "разорвана связь с сервером"
2) Просто долгая загрузка и в конце "разорвана связь с сервером"
3) Загрузка ресурс-пака 70-80%/100%

**Comment by HotRikardo228** [comment]
Я могу зайти.
![Screenshot_20200101-234737_Minecraft](https://user-images.githubusercontent.com/59420530/71645993-484d7e00-2cf1-11ea-8b63-d0dd37c3394e.jpg)

**Comment by DanilDre** [comment]
Не могу зайти: версия игры — 1.14.0, страна — Беларусь, интернет — быстрый. ( интернет хороший, проблем нет)

**Comment by KUKUzka** [comment]
Не могу зайти :
Версия-1.14.0
Страна- Россия
Интернет - Быстрый, хороший.

Заходит на сервер, в течении 15 секунд вылетает с данным фото (Фото не прикрепила, так как не знаю как это сделать. Хотя все кнопки пережмакала) . Далее, если попытаюсь зайти, просто не заходит 

`

**Comment by StormLVV** [comment]
Внимание! При вылете с сервера или "вечной" загрузке попробуйье полностью удалить кэш с Майнкрафта и заново зайти на сервер! Есть шанс устранить проблему!

**Comment by FirzMob** [comment]
Невозможно мне зайти на сервер при версии игры 1.14.1, живя при этом в России и имея скорость инета в 600 кб/с. Очистка кэша не спасает.

**Comment by FedyaShi** [comment]
Не могу зайти на сервер. Версия игры 1.14.1, Россия, скорость интернета 3мбит/сек. Очистка кэша не помогает
![Screenshot_2020-01-02-12-08-11-330_com mojang minecraftpe](https://user-images.githubusercontent.com/59420793/71655531-0b1cd680-2d59-11ea-8dcc-afc0154f77a4.jpg)

**Comment by NaRcKoMaN** [comment]
Я могу зайти на сервер.
Версия игры 1.14.0.2

**Comment by YnurPanda** [comment]
Зашло без всяких проблем установилось 5мб вместо 40мб текстур(ну или больше я не помню) а так всё ровно.
![Screenshot_20200102-124149_Minecraft](https://user-images.githubusercontent.com/59420643/71661026-f262ef80-2d5d-11ea-926f-1bb5906bbcf8.jpg)

**Comment by UnicornLeet** [comment]
Я могу зайти

**Comment by UnicornLeet** [comment]
Я могу зайти

**Comment by GGWP5** [comment]
Я могу зайти

**Comment by DanilDre** [comment]
Не могу зайти, не загружаются ресурсы, потом пишет "Разорвано соединение с сервером"

**Comment by MrMilkerYT** [comment]
Не могу зайти на сервер!
1. 1.14.1
2. Россия (Город: Южно-Сахалинск)
3. Интернет: super!

Проблема:
Не грузит ресурсы пакета, не двигается с 0%

**Comment by enerhard** [comment]
Не могу зайти на сервер
Minecraft v1.14.2
Страна: Россия 
Интернет: более менее
Не грузятся ресурсы

**Comment by Makcim212** [comment]
Я могу зайти 
![Screenshot_20200103_210759_com mojang minecraftpe](https://user-images.githubusercontent.com/59478711/71740461-50cac380-2e6d-11ea-91ba-8148e0efa04e.jpg)

**Comment by GGWP5** [comment]
Человек из беседы игроков не может зайти,у него вечная загрузка текстур.Страна Россия,версия игры 1.14.1,интернет 65 МБит/сек.Ждёт возможных решений.
![aSJ32NqyvD8](https://user-images.githubusercontent.com/59420848/71753029-58509380-2e92-11ea-89a8-ea54bb167103.jpg)
