### ISSUE TITLE
Не зарегестрирован магазин по координатам -341 196.

### ISSUE THREAD

**Issue by HotRikardo228** [mcrpg/work#9]
Не зарегестрирован магазин по координатам -341 196. 
 @![jwGodEdeVdU](https://user-images.githubusercontent.com/59420530/71654816-c5eea980-2d44-11ea-9d4c-7f45708e5ac2.jpg)

**Comment by HotRikardo228** [comment]
Найден ещё один незарегестрированный магазин на координатах -271 137
![Screenshot_20200102-122609_Minecraft](https://user-images.githubusercontent.com/59420530/71660312-b3339f00-2d5b-11ea-8f38-318a83de18d8.jpg)

**Comment by HotRikardo228** [comment]
log 30m - зарегестрировал часть магазина
![Screenshot_20200102-135203_Minecraft](https://user-images.githubusercontent.com/59420530/71683627-1f39f580-2da4-11ea-8aaa-3ec9414f8b2e.jpg)

**Comment by UnicornLeet** [comment]
log 40m - зарегистрировал часть магазина

**Comment by UnicornLeet** [comment]
log 40m - зарегистрировал часть магазина

**Comment by UnicornLeet** [comment]
log 40m - зарегистрировал часть магазина

**Comment by UnicornLeet** [comment]
log 40m - зарегистрировал часть магазина
https://vk.com/photo332569122_457240798

**Comment by UnicornLeet** [comment]
log 40m - зарегистрировал часть магазина
https://vk.com/photo332569122_457240798

**Comment by UnicornLeet** [comment]
log 40m - зарегистрировал часть магазина
https://sun9-68.userapi.com/c858032/v858032422/142b24/wV-J4UAxzAg.jpg

**Comment by FirzMob** [comment]
> log 40m - зарегистрировал часть магазина
> https://sun9-68.userapi.com/c858032/v858032422/142b24/wV-J4UAxzAg.jpg

В магазине по координатам -341 196 нет данных табличек!

**Comment by ProCompTEAM** [comment]
Обновления по задаче кидать в #26
